### ISSUE TITLE
More detailed docs

### ISSUE THREAD

**Issue by platform-kit** [rubbrband/rubbrband#1]
**Problem:** It's unclear what is meant to be contained in the `./data` directory.

**Proposed solution:** Please add specifics about what is required for each model.

**Comment by jrmylee** [comment]
added link to more detailed docs in https://github.com/rubbrband/rubbrband/commit/2fc53fc9a20dee67a645e924b6c0dc195f8584c8

**Comment by darhsu** [comment]
Hey @platform-kit, thanks for the feedback! We've updated the docs with detailed descriptions for each flag 😄
