### ISSUE TITLE
Unable to train Rubbrband via the command line

### ISSUE THREAD

**Issue by jackson-sandland** [rubbrband/rubbrband#16]
I'm on an M1 Mac Mini. I'm in a `virtualenv` and running: `rubbrband train dreambooth --class-word man --dataset-dir ./sample_dataset --reg-dir ./regDir --log-dir ./logs` in the terminal and see this error, which is also mentioned in the docs: 

```
Docker is not running as root. Please start Docker or run sudo su root
```
The docs say the solution for this is: `If you get this error, you need to install Docker.`

I do have docker installed though and it's running locally. What do I need to do to be able to run this command? Is there a docker image I can pull that will help solve this?

**Comment by jrmylee** [comment]
Yeah sadly this is a known issue with the docker-python client. Can you run this in your python interpreter and send your output here?

```
import docker
client = docker.from_env()
```

**Comment by jackson-sandland** [comment]
```
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'docker'
>>> 
```
If I run `pip install docker` outside of the python interpreter (just in the terminal in the virtual env) I get: 
```
(venv) ${whoami} test % pip install docker
Requirement already satisfied: docker in ./venv/lib/python3.9/site-packages (6.1.1)
Requirement already satisfied: urllib3>=1.26.0 in ./venv/lib/python3.9/site-packages (from docker) (2.0.2)
Requirement already satisfied: websocket-client>=0.32.0 in ./venv/lib/python3.9/site-packages (from docker) (1.5.1)
Requirement already satisfied: packaging>=14.0 in ./venv/lib/python3.9/site-packages (from docker) (23.1)
Requirement already satisfied: requests>=2.26.0 in ./venv/lib/python3.9/site-packages (from docker) (2.30.0)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages (from requests>=2.26.0->docker) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.9/site-packages (from requests>=2.26.0->docker) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests>=2.26.0->docker) (2023.5.7)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
```

If I create a file and add `import docker` to the top and then run the file I get: 
```
Traceback (most recent call last):
  File "/Users/${whoami}/test/./test.py", line 1, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
```
It doesn't make it far enough to run `client = docker.from_env()`

**Comment by jackson-sandland** [comment]
Were changes made? It's suddenly working!
<img width="564" alt="Screenshot 2023-05-11 at 6 42 08 PM" src="https://github.com/rubbrband/rubbrband/assets/4956122/bc18e86e-be68-4ce4-a862-98d4cec4019a">

**Comment by jrmylee** [comment]
Nope! no changes. Maybe you're now in the env with docker-python is installed?
